CREATE TABLE IF NOT EXISTS mpa
(
    id  INTEGER PRIMARY KEY,
    mpa VARCHAR NOT NULL
);


CREATE TABLE IF NOT EXISTS films
(
    id           INTEGER GENERATED BY DEFAULT  AS IDENTITY(START WITH 0) PRIMARY KEY,
    name         VARCHAR      NOT NULL,
    description  VARCHAR(200) NOT NULL,
    release_date DATE         NOT NULL,
    duration     INTEGER      NOT NULL,
    mpa_id       INTEGER,
    FOREIGN KEY (mpa_id)
        REFERENCES mpa (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS users
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR NOT NULL,
    login    VARCHAR NOT NULL UNIQUE,
    email    VARCHAR NOT NULL UNIQUE,
    birthday DATE    NOT NULL,
    CONSTRAINT birthday_check CHECK (birthday < CURRENT_DATE)
);

CREATE TABLE IF NOT EXISTS friendships
(
    user1_id INTEGER NOT NULL,
    user2_id INTEGER NOT NULL,
    status   VARCHAR NOT NULL,
    PRIMARY KEY (user1_id, user2_id),
    FOREIGN KEY (user1_id)
        REFERENCES users (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (user2_id)
        REFERENCES users (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS liked_films
(
    user_id INTEGER NOT NULL,
    film_id INTEGER NOT NULL,
    PRIMARY KEY (user_id, film_id),
    FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (film_id)
        REFERENCES films (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS genres
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS films_genres
(
    genre_id INTEGER,
    film_id  INTEGER NOT NULL,
    FOREIGN KEY (genre_id)
        REFERENCES genres (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (film_id)
        REFERENCES films (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
