CREATE TABLE IF NOT EXISTS films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR,
    description VARCHAR,
    release_date DATE,
    duration INTEGER
    );

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR,
    login VARCHAR,
    email VARCHAR,
    birthday DATE
    );

CREATE TABLE IF NOT EXISTS friendships (
    user1_id INTEGER,
    user2_id INTEGER,
    status VARCHAR,
    PRIMARY KEY (user1_id, user2_id),
    FOREIGN KEY (user1_id)
        REFERENCES users (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (user2_id)
        REFERENCES users (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
    );

CREATE TABLE IF NOT EXISTS liked_films (
    user_id INTEGER,
    film_id INTEGER,
    PRIMARY KEY (user_id, film_id),
    FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (film_id)
        REFERENCES films (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS genres (
    genre VARCHAR,
    film_id INTEGER,
    PRIMARY KEY (genre, film_id),
    FOREIGN KEY (film_id)
        REFERENCES films (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);